### ISSUE TITLE
Transfer error

### ISSUE THREAD

**Issue by Gondagar** [homura/pw-up#20]
Hello,

please help me with this error. I can't transfer bnb tokens.   

I am trying to send coins through an SFP wallet.

![photo_2022-04-21_13-43-17](https://user-images.githubusercontent.com/13300339/164442430-8bbcbca0-13fc-403d-ba8a-1b5da164d073.jpg)

**Comment by homura** [comment]
Hi, @Gondagar this bug has been fixed, can you try again?

**Comment by Gondagar** [comment]
The bug has indeed been fixed. Thank you very much

![photo_2022-04-21_17-06-36](https://user-images.githubusercontent.com/13300339/164476013-ed2a8a85-8052-40b3-a02c-591dc1bf7d9c.jpg)
